default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  pool: 5

development:
  <<: *default
  database: speakerline_development

test: &test
  <<: *default
  database: speakerline_test

production:
  <<: *default
  database: speakerline_production

cucumber:
  <<: *test
